apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: todo-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo-container
        image: todo-app:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8000

        envFrom:
        - configMapRef:
            name: todo-config

        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"

        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5